trigger:
  branches:
    include: [main, develop, "release-*" ]
  paths:
    exclude: ["*.md", .gitignore]
  tags:
    include: ["v*"]

# PR always trigger build

# add nf-tools repo to resources (for Azure Pipelines templates)
resources:
  repositories:
    - repository: templates
      type: github
      name: nanoframework/nf-tools
      endpoint: nanoframework
     
jobs:

##############################
- job: Build_Library
  condition: or( eq(variables['UPDATE_DEPENDENTS'], 'false'), eq(variables['StartReleaseCandidate'], 'true') )
  pool:
    vmImage: 'windows-2019'

  variables:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    nugetPackageName: 'nanoFramework.System.Text.RegularExpressions'
    repoName: 'nanoFramework.System.Text.RegularExpressions'

  steps:

  # step from template @ nf-tools repo
  # all build, update and publish steps
  - template: azure-pipelines-templates/class-lib-build.yml@templates
    parameters:
      sonarCloudProject: 'nanoframework_lib-nanoFramework.System.Text.RegularExpressions'
      runUnitTests: true
      unitTestRunsettings: '$(System.DefaultWorkingDirectory)\Tests\NFUnitTestRegex\nano.runsettings'
  
##################################
# report build failure to Discord
- job: Report_Build_Failure

  dependsOn:
  - Build_Library
  condition: or( failed('Build_Library'), failed('Update_Dependents'))

  pool:
    vmImage: 'windows-2019'
  steps:

  - checkout: self
      
  # step from template @ nf-tools repo
  # report error
  - template: azure-pipelines-templates/discord-webhook-task.yml@templates  
    parameters:
      status: 'failure'
      webhookUrl: '$(DiscordWebhook)'
      message: ''
